///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DeliverySlotModel {
/*
{
  "Delivery_date": "02-03-2022",
  "Delivery_day": "Wednesday"
}
*/

  String? deliveryDate;
  String? deliveryDay;

  DeliverySlotModel({
    this.deliveryDate,
    this.deliveryDay,
  });
  DeliverySlotModel.fromJson(Map<String, dynamic> json) {
    deliveryDate = json['Delivery_date']?.toString();
    deliveryDay = json['Delivery_day']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Delivery_date'] = deliveryDate;
    data['Delivery_day'] = deliveryDay;
    return data;
  }
}
