///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Offer {
/*
{
  "id": "4",
  "name": "15% OFF on Amul cheese",
  "image": "https://appsontechnologies.in/digitizationApp/uploads/amul-cheese-block-200-g-carton-0-20201111.jpg",
  "valid_to": "2022-03-20",
  "valid_from": "2022-03-12",
  "description": "Amul Cheese offer"
}
*/

  String? id;
  String? name;
  String? image;
  String? validTo;
  String? validFrom;
  String? description;

  Offer({
    this.id,
    this.name,
    this.image,
    this.validTo,
    this.validFrom,
    this.description,
  });
  Offer.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    image = json['image']?.toString();
    validTo = json['valid_to']?.toString();
    validFrom = json['valid_from']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['valid_to'] = validTo;
    data['valid_from'] = validFrom;
    data['description'] = description;
    return data;
  }
}
