///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderProductModel {
/*
{
  "product_id": "1",
  "quantity": "2",
  "total_price": "100",
  "total_amount": "50"
} 
*/

  String? productId;
  String? quantity;
  String? totalPrice;
  String? totalAmount;
  String? totalDiscount;
  String? disAmount;

  OrderProductModel({
    this.productId,
    this.quantity,
    this.totalPrice,
    this.totalAmount,
    this.totalDiscount,
    this.disAmount,
  });
  OrderProductModel.fromJson(Map<String, dynamic> json) {
    productId = json['product_id']?.toString();
    quantity = json['quantity']?.toString();
    totalPrice = json['total_price']?.toString();
    totalAmount = json['total_amount']?.toString();
    totalDiscount = json['total_discount']?.toString();
    disAmount = json['discount_price']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['product_id'] = productId;
    data['quantity'] = quantity;
    data['total_price'] = totalPrice;
    data['total_amount'] = totalAmount;
    data['total_discount'] = totalDiscount;
    data['discount_price'] = disAmount;
    return data;
  }
}

class PlaceOrderModel {
/*
{
  "token": "",
  "product": [
    {
      "product_id": "1",
      "quantity": "2",
      "total_price": "100",
      "total_amount": "50"
    }
  ],
  "total_items": 2,
  "city": "",
  "state": "",
  "region": "",
  "country": "",
  "references": "",
  "delivery_address": "",
  "delivery_location": ""
} 
*/

  String? token;
  String? product;
  String? totalItems;
  String? totalAmount;
  String? city;
  String? state;
  String? region;
  String? country;
  String? references;
  String? deliveryAddress;
  String? deliveryLocation;

  PlaceOrderModel({
    this.token,
    this.product,
    this.totalItems,
    this.totalAmount,
    this.city,
    this.state,
    this.region,
    this.country,
    this.references,
    this.deliveryAddress,
    this.deliveryLocation,
  });
  PlaceOrderModel.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
    // if (json['product'] != null) {
    //   final v = json['product'];
    //   final arr0 = <OrderProductModel>[];
    //   v.forEach((v) {
    //     arr0.add(OrderProductModel.fromJson(v));
    //   });
    //   product = arr0;
    // }
    product = json['products']?.toString();
    totalItems = json['total_items']?.toInt();
    totalAmount = json['total_amount'];
    city = json['city']?.toString();
    state = json['state']?.toString();
    region = json['region']?.toString();
    country = json['country']?.toString();
    references = json['references']?.toString();
    deliveryAddress = json['delivery_address']?.toString();
    deliveryLocation = json['delivery_location']?.toString();
  }
  Map<String, String> toJson() {
    final data = <String, String>{};
    data['token'] = token!;
    data['products'] = product!;
    // if (product != null) {
    //   final v = product;
    //   final arr0 = [];
    //   for (var v in v!) {
    //     arr0.add(v!.toJson());
    //   }
    //   data['product'] = arr0;
    // }
    data['total_items'] = totalItems!;
    data["total_amount"] = totalAmount!;
    data['city'] = city!;
    data['state'] = state!;
    data['region'] = region!;
    data['country'] = country!;
    data['references'] = references!;
    data['delivery_address'] = deliveryAddress!;
    data['delivery_location'] = deliveryLocation!;
    return data;
  }
}
