///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class User {
/*
{
  "id": "2",
  "name": "sonika",
  "business_name": "testing",
  "rut": "hhh",
  "email": "sonika.2496@gmail.com",
  "password": "827ccb0eea8a706c4c34a16891f84e7b",
  "confirm_password": "12345",
  "contact": "123654789",
  "alternate_contact": "7566213655",
  "address": "vijaynagar",
  "delivery_address": null,
  "city": "indore",
  "region": "xyz",
  "country": "india",
  "state": "madhyapradesh",
  "image": null,
  "status": "active",
  "reference": "xyz",
  "latitude": "22.7196",
  "longitude": "75.8577",
  "route_id": "0",
  "device_id": "1236548895vcvcbcb",
  "added": "2022-02-1804:13:27",
  "modified": "2022-02-18 04:13:27"
}
*/

  String? userId;
  String? name;
  String? businessName;
  String? rut;
  String? email;
  String? password;
  String? confirmPassword;
  String? contact;
  String? alternateContact;
  String? address;
  String? deliveryAddress;
  String? city;
  String? region;
  String? country;
  String? state;
  String? image;
  String? status;
  String? reference;
  String? latitude;
  String? longitude;
  String? routeId;
  String? deviceId;
  String? added;
  String? modified;

  User({
    this.userId,
    this.name,
    this.businessName,
    this.rut,
    this.email,
    this.password,
    this.confirmPassword,
    this.contact,
    this.alternateContact,
    this.address,
    this.deliveryAddress,
    this.city,
    this.region,
    this.country,
    this.state,
    this.image,
    this.status,
    this.reference,
    this.latitude,
    this.longitude,
    this.routeId,
    this.deviceId,
    this.added,
    this.modified,
  });
  User.fromJson(Map<String, dynamic> json) {
    userId = json['id']?.toString();
    name = json['name']?.toString();
    businessName = json['business_name']?.toString();
    rut = json['rut']?.toString();
    email = json['email']?.toString();
    password = json['password']?.toString();
    confirmPassword = json['confirm_password']?.toString();
    contact = json['contact']?.toString();
    alternateContact = json['alternate_contact']?.toString();
    address = json['address']?.toString();
    deliveryAddress = json['delivery_address']?.toString();
    city = json['city']?.toString();
    region = json['region']?.toString();
    country = json['country']?.toString();
    state = json['state']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toString();
    reference = json['reference']?.toString();
    latitude = json['latitude']?.toString();
    longitude = json['longitude']?.toString();
    routeId = json['route_id']?.toString();
    deviceId = json['device_id']?.toString();
    added = json['added']?.toString();
    modified = json['modified']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = userId;
    data['name'] = name;
    data['business_name'] = businessName;
    data['rut'] = rut;
    data['email'] = email;
    data['password'] = password;
    data['confirm_password'] = confirmPassword;
    data['contact'] = contact;
    data['alternate_contact'] = alternateContact;
    data['address'] = address;
    data['delivery_address'] = deliveryAddress;
    data['city'] = city;
    data['region'] = region;
    data['country'] = country;
    data['state'] = state;
    data['image'] = image;
    data['status'] = status;
    data['reference'] = reference;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['route_id'] = routeId;
    data['device_id'] = deviceId;
    data['added'] = added;
    data['modified'] = modified;
    return data;
  }
}
